# -*- coding: utf-8 -*-
"""CentreLimitTheorem.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11MQgv_A1A7j5ZGfUYn-0lJvBcwEeKjFi

**Centre Limit Theorem**:The sampling distribution of the sample mean approaches a normal distribution as the sample size increases, regardless of the shape of the population distribution, provided the samples are independent and identically distributed (i.i.d.).

We will break it down word by word. Sampling distribution of sample mean, **the distribution of means off all the possible samples taken from a population**.
"""

import numpy as np
import random
import matplotlib.pyplot as plt
# Define an empty numpy array with a shape of (3, 3)

totalPopulation = [0,1000] # all sample values will be more thann 0 and less than 1.

totalDataPointsinPopulation = 1000
numberOfSamples =  random.randint(1, totalDataPointsinPopulation)
arr = np.empty((0, 2))
for j in range(1,100000):
  sample_size = random.randint(1, totalDataPointsinPopulation)
  random_numbers = np.random.uniform(0, totalDataPointsinPopulation, sample_size)
  mean_value = np.mean(random_numbers)
  new_row = np.array([sample_size, mean_value])
  arr = np.append(arr, [new_row], axis=0)

population = np.random.uniform(0, totalDataPointsinPopulation, totalDataPointsinPopulation)
populationMean = np.mean(population)

# Add the new row using np.append()

"""According to the **Law of Large Numbers**, as the sample size increases, the sample mean tends to get closer to the true population mean. The plot will visually reflect this as the sample mean converging to a specific value (the population mean)"""

sample_size = arr[:, 0]  # First column (x-values)
means = arr[:, 1]  # Second column (y-values)

# Plot the data
plt.plot(means,sample_size, marker='o', label="SampleMeans")
plt.plot(populationMean, totalDataPointsinPopulation, 'ro', label='PopulationMean')

plt.title("Sample Size Vs Means")
plt.xlabel("means")
plt.ylabel("sample size")
plt.legend()
plt.grid(True)
plt.show()

"""Below: The **CLT** states that regardless of the original population distribution, as the sample size increases, the distribution of sample means will approach a normal distribution centered around the population mean. In practice, this means that the plot of sample size vs. mean should show convergence of the sample means as the sample size increases.

**Stabilization of Sample Mean:**

As the sample size increases, the sample mean becomes more stable and approaches the population mean (if you're sampling from a known population). This reflects the idea that the sample mean is an unbiased estimator of the population mean.

**Reduction in Variability:**

For small sample sizes, the sample mean can vary more because there are fewer data points to average. The plot will show larger variability in the sample means.
As the sample size increases, the sample mean becomes less variable. The spread (standard deviation) of the sample means gets smaller, which means the sample mean is a more reliable estimate of the population mean
"""

plt.hist(means, bins=30, edgecolor='black', alpha=0.7)